import Cocoa

/// Clawd's scenes, drawn rather than shipped. Each pose is text art on a grid of
/// 22 × 12 square pixels, one character per pixel — edit a pose by editing its
/// picture. The walk is not here: it is the GIF's own frames (`CrabFrames.swift`).
///
/// | Mark | Drawn as |
/// | --- | --- |
/// | `o` `O` | body, body in shade |
/// | `#` | eye |
/// | `=` | laptop |
/// | `w` `g` `b` `B` | page, printed line, book cover, cover corner |
/// | `k` `c` `s` | lens rim, lens glass, glint |
/// | `n` `h` `a` | hammer handle, hammer head, anvil |
/// | `y` `Y` | spark (and the amber "!"), dying spark |
/// | `r` `v` `V` | antenna tip, fresh wave (and the blue "?"), fading wave |
/// | `t` `T` `q` | cardboard, tape and flaps, the stuff that won't fit |
/// | `m` `M` | thought dots, puffs of air, a z; a fading z |
/// | `.` | empty |
///
/// Colours are chosen for both of the mark's modes: in System mode
/// `IconRenderer.adaptiveTemplate` turns luminance into ink, so anything that must
/// stay apart from the body there (a cover, a lens, a wave) is darker than it.
enum ClawdSceneArt {
    static let columns = 22
    static let rows = 12

    static let palette: [Character: UInt32] = [
        "o": 0xd77757, "O": 0xbd674b, "#": 0x000000, "=": 0x898989,
        "w": 0xf2f2f2, "g": 0x7a7a7a, "b": 0x4c7bd9, "B": 0x3a62b4,
        "k": 0x9a9a9a, "c": 0x2e4a5c, "s": 0xffffff,
        "n": 0xa8763e, "h": 0xc4c4c4, "a": 0x8a8a8a, "y": 0xf5c542, "Y": 0xf08a2b,
        "r": 0xe5534b, "v": 0x8ab4f8, "V": 0x4f6e9c,
        "t": 0xc8955c, "T": 0x8e6234, "q": 0xe8d3a8, "m": 0xd8d8d8, "M": 0x6a6a6a,
    ]

    /// `pose` drawn `pixel` points to a pixel, at the left of a canvas
    /// `canvasWidth` wide — only the marks in `only`, when it is given.
    static func image(_ pose: String, pixel: CGFloat, canvasWidth: CGFloat,
                      only: Set<Character>? = nil) -> NSImage {
        let lines = pose.split(separator: "\n")
        let out = NSImage(size: NSSize(width: canvasWidth, height: CGFloat(rows) * pixel))
        out.lockFocus()
        for (y, line) in lines.enumerated() {
            for (x, mark) in line.enumerated() {
                guard let rgb = palette[mark], only?.contains(mark) ?? true else { continue }
                NSColor(srgbRed: CGFloat(rgb >> 16 & 0xff) / 255,
                        green: CGFloat(rgb >> 8 & 0xff) / 255,
                        blue: CGFloat(rgb & 0xff) / 255, alpha: 1).setFill()
                NSRect(x: CGFloat(x) * pixel, y: CGFloat(rows - 1 - y) * pixel,
                       width: pixel, height: pixel).fill()
            }
        }
        out.unlockFocus()
        return out
    }
}

extension ClawdScene {
    /// A scene's poses, and which pose plays on each frame of its loop.
    struct Reel {
        let rhythm: [Int]
        let poses: [String]
    }

    /// Marks that keep their colour in System mode, where everything else turns
    /// to ink: the "!" and the "?" say what the badge dot used to, and the dot was
    /// never monochrome either.
    var keepsColour: Set<Character> {
        switch self {
        case .approve: return ["y"]
        case .ask:     return ["v"]
        default:       return []
        }
    }

    /// Nil for the walk, which plays the GIF.
    var reel: Reel? {
        switch self {
        case .walk:
            return nil
        case .think:
            // Facing you, arms out, eyes up and to the right, bobbing
            // while three dots fill in: standing tall with none, two and
            // three dots, then bobbed down with none, one and three.
            return Reel(rhythm: [0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 5, 5, 5, 5,
                                 5, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
                        poses: [
                """
                ..oooooooooooo........
                ..ooo##oooo##o........
                ..ooo##oooo##o........
                ..oooooooooooo........
                oooooooooooooooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
                """
                ..oooooooooooo........
                ..ooo##oooo##o...m.m..
                ..ooo##oooo##o........
                ..oooooooooooo........
                oooooooooooooooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
                """
                ..oooooooooooo........
                ..ooo##oooo##o...m.m.m
                ..ooo##oooo##o........
                ..oooooooooooo........
                oooooooooooooooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
                """
                ......................
                ......................
                ..oooooooooooo........
                ..ooo##oooo##o........
                ..ooo##oooo##o........
                ..oooooooooooo........
                oooooooooooooooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
                """
                ......................
                .................m....
                ..oooooooooooo........
                ..ooo##oooo##o........
                ..ooo##oooo##o........
                ..oooooooooooo........
                oooooooooooooooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
                """
                ......................
                .................m.m.m
                ..oooooooooooo........
                ..ooo##oooo##o........
                ..ooo##oooo##o........
                ..oooooooooooo........
                oooooooooooooooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
            ])
        case .type:
            // At the laptop: hand up, pressing, resting on the keys.
            return Reel(rhythm: [0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2, 1, 0,
                                 1, 0, 1, 2, 2],
                        poses: [
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##.........=
                oo##oooooo##.........=
                oooooooooooooooo....=.
                oooooooooooooooo....=.
                oooooooooooooooo...=..
                oooooooooooooooo...=..
                oo....oo..oo.======...
                oo....oo..oo.======...
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##..........
                oooooooooooooo.......=
                oooooooooooooo.......=
                ooooooooooooOOOO....=.
                ooooooooooooOOOO....=.
                oo....oo..oo..OO...=..
                oo....oo..oo..OO...=..
                o.....o...o..======...
                o.....o...o..======...
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##..........
                oooooooooooooooo.....=
                oooooooooooooooo.....=
                oooooooooooo........=.
                oooooooooooo........=.
                oo....oo..oo.......=..
                oo....oo..oo.......=..
                o.....o...o..======...
                o.....o...o..======...
                """,
            ])
        case .read:
            // An open book held up; it nods, and now and then a page
            // turns: lifts on the right, stands on the spine, lands on
            // the left.
            return Reel(rhythm: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2,
                                 2, 3, 3, 4, 4, 0, 0, 0, 0],
                        poses: [
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##.ww.....ww
                oo##oooooo##.bwwwBwwwb
                oooooooooooo.bggwBwggb
                oooooooooooo.bwwwBwwwb
                ooooooooooooobgwwBwggb
                ooooooooooooobbbbbbbbb
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##.ww.....ww
                oooooooooooo.bwwwBwwwb
                oooooooooooo.bggwBwggb
                ooooooooooooobwwwBwwwb
                ooooooooooooobgwwBwggb
                oo....oo..oo.bbbbbbbbb
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo.......ww.
                oooooooooooo.......ww.
                oo##oooooo##.ww...w.ww
                oo##oooooo##.bwwwBwwwb
                oooooooooooo.bggwBwggb
                oooooooooooo.bwwwBwwwb
                ooooooooooooobgwwBwggb
                ooooooooooooobbbbbbbbb
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo.....w....
                oooooooooooo.....w....
                oo##oooooo##.ww..w..ww
                oo##oooooo##.bwwwwwwwb
                oooooooooooo.bggwwwggb
                oooooooooooo.bwwwwwwwb
                ooooooooooooobgwwwwggb
                ooooooooooooobbbbbbbbb
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo...ww.....
                oooooooooooo...ww.....
                oo##oooooo##.ww..w..ww
                oo##oooooo##.bwwwBwwwb
                oooooooooooo.bggwBwggb
                oooooooooooo.bwwwBwwwb
                ooooooooooooobgwwBwggb
                ooooooooooooobbbbbbbbb
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
            ])
        case .search:
            // A magnifier swept across, with a pause where something
            // caught his eye.
            return Reel(rhythm: [0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5,
                                 5, 5],
                        poses: [
                """
                oooooooooooo..........
                oooooooooooo....kkk...
                oo##oooooo##...kcsck..
                oo##oooooo##...kccck..
                oooooooooooo...kccck..
                oooooooooooo....kkk...
                oooooooooooooonn......
                oooooooooooooo........
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo.....kkk..
                oooooooooooo....kcsck.
                oo##oooooo##....kccck.
                oo##oooooo##....kccck.
                oooooooooooo.....kkk..
                oooooooooooo....n.....
                ooooooooooooooon......
                ooooooooooooooo.......
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo......kkk.
                oooooooooooo.....kcsck
                oo##oooooo##.....kccck
                oo##oooooo##.....kccck
                oooooooooooo......kkk.
                oooooooooooo.....n....
                oooooooooooooooon.....
                oooooooooooooooo......
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo..........
                oooooooooooo......kkk.
                oo##oooooo##.....kcsck
                oo##oooooo##.....kccck
                oooooooooooo.....kccck
                oooooooooooo......kkk.
                oooooooooooooooonn....
                oooooooooooooooo......
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo..........
                oooooooooooo.....kkk..
                oo##oooooo##....kcsck.
                oo##oooooo##....kccck.
                oooooooooooo....kccck.
                oooooooooooo.....kkk..
                ooooooooooooooonn.....
                ooooooooooooooo.......
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo....kkk...
                oooooooooooo...kcsck..
                oo##oooooo##...kccck..
                oo##oooooo##...kccck..
                oooooooooooo....kkk...
                oooooooooooo...n......
                oooooooooooooon.......
                oooooooooooooo........
                oo....oo..oo..........
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
            ])
        case .hammer:
            // Hammer up, swing, strike, sparks, sparks fading.
            return Reel(rhythm: [0, 0, 0, 0, 1, 2, 3, 3, 4, 4, 1, 0, 0, 0, 0, 1, 2, 3, 3,
                                 4, 4, 1],
                        poses: [
                """
                oooooooooooo...hh.....
                oooooooooooo..nhh.....
                oo##oooooo##.n........
                oo##oooooo##oo........
                oooooooooooooo........
                oooooooooooooo........
                oooooooooooo..........
                oooooooooooo..........
                oo....oo..oo...aaaaaaa
                oo....oo..oo....aaaaa.
                o.....o...o......aaa..
                o.....o...o.....aaaaa.
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##.....hh...
                oo##oooooo##.....hh...
                oooooooooooooonnnhh...
                oooooooooooooo...hh...
                oooooooooooo..........
                oooooooooooo..........
                oo....oo..oo...aaaaaaa
                oo....oo..oo....aaaaa.
                o.....o...o......aaa..
                o.....o...o.....aaaaa.
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##..........
                oooooooooooo......hh..
                oooooooooooo......hh..
                ooooooooooooooonnnhh..
                ooooooooooooooo...hh..
                oo....oo..oo...aaaaaaa
                oo....oo..oo....aaaaa.
                o.....o...o......aaa..
                o.....o...o.....aaaaa.
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##........y.
                oo##oooooo##..........
                oooooooooooo....y.hh.y
                oooooooooooo......hh..
                ooooooooooooooonnnhh.y
                ooooooooooooooo...hh..
                oo....oo..oo...aaaaaaa
                oo....oo..oo....aaaaa.
                o.....o...o......aaa..
                o.....o...o.....aaaaa.
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##.........Y
                oo##oooooo##.....Y...Y
                oooooooooooo......hh..
                oooooooooooo......hh..
                ooooooooooooooonnnhh..
                ooooooooooooooo...hh..
                oo....oo..oo...aaaaaaa
                oo....oo..oo....aaaaa.
                o.....o...o......aaa..
                o.....o...o.....aaaaa.
                """,
            ])
        case .web:
            // An antenna, its waves rolling out one ring after another.
            return Reel(rhythm: [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 0, 0, 0, 1,
                                 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
                        poses: [
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..r.......
                oo##oooooo##..a.......
                ooooooooooooooa.......
                ooooooooooooooa.......
                oooooooooooo..a.......
                oooooooooooo..a.......
                oo....oo..oo..a.......
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo..........
                oooooooooooo....v.....
                oo##oooooo##..r..v....
                oo##oooooo##..a.v.....
                ooooooooooooooa.......
                ooooooooooooooa.......
                oooooooooooo..a.......
                oooooooooooo..a.......
                oo....oo..oo..a.......
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo......v...
                oooooooooooo....V..v..
                oo##oooooo##..r..V.v..
                oo##oooooo##..a.V..v..
                ooooooooooooooa...v...
                ooooooooooooooa.......
                oooooooooooo..a.......
                oooooooooooo..a.......
                oo....oo..oo..a.......
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo......V.v.
                oooooooooooo.......V.v
                oo##oooooo##..r....V.v
                oo##oooooo##..a....V.v
                ooooooooooooooa...V.v.
                ooooooooooooooa.......
                oooooooooooo..a.......
                oooooooooooo..a.......
                oo....oo..oo..a.......
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
                """
                oooooooooooo........V.
                oooooooooooo.........V
                oo##oooooo##..r......V
                oo##oooooo##..a......V
                ooooooooooooooa.....V.
                ooooooooooooooa.......
                oooooooooooo..a.......
                oooooooooooo..a.......
                oo....oo..oo..a.......
                oo....oo..oo..........
                o.....o...o...........
                o.....o...o...........
                """,
            ])
        case .delegate:
            // A little Clawd steps along beside him, its legs taking
            // turns; now and then the big one waves to it.
            return Reel(rhythm: [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 2,
                                 2, 2, 3, 3, 3],
                        poses: [
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##..........
                ooooooooooooo.........
                ooooooooooooo.........
                oooooooooooo..ooooooo.
                oooooooooooo..o#ooo#o.
                oo....oo..oo.ooooooooo
                oo....oo..oo..ooooooo.
                o.....o...o...o.o.o.o.
                o.....o...o...o.....o.
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##..........
                ooooooooooooo.........
                ooooooooooooo.........
                oooooooooooo..ooooooo.
                oooooooooooo..o#ooo#o.
                oo....oo..oo.ooooooooo
                oo....oo..oo..ooooooo.
                o.....o...o...o.o.o.o.
                o.....o...o.....o.o...
                """,
                """
                oooooooooooo..........
                oooooooooooo.o........
                oo##oooooo##oo........
                oo##oooooo##o.........
                ooooooooooooo.........
                ooooooooooooo.........
                oooooooooooo..ooooooo.
                oooooooooooo..o#ooo#o.
                oo....oo..oo.ooooooooo
                oo....oo..oo..ooooooo.
                o.....o...o...o.o.o.o.
                o.....o...o...o.....o.
                """,
                """
                oooooooooooo..........
                oooooooooooo.o........
                oo##oooooo##oo........
                oo##oooooo##o.........
                ooooooooooooo.........
                ooooooooooooo.........
                oooooooooooo..ooooooo.
                oooooooooooo..o#ooo#o.
                oo....oo..oo.ooooooooo
                oo....oo..oo..ooooooo.
                o.....o...o...o.o.o.o.
                o.....o...o.....o.o...
                """,
            ])
        case .compact:
            // Squashing an overfull box shut: full, pushed, shut, a puff
            // of air.
            return Reel(rhythm: [0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2,
                                 2],
                        poses: [
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##.....qq...
                oo##oooooo##....qqqq..
                ooooooooooooooT.qqqq.T
                oooooooooooooo.TqqqqT.
                oooooooooooo..tttttttt
                oooooooooooo..tttTTttt
                oo....oo..oo..tttTTttt
                oo....oo..oo..tttttttt
                o.....o...o...tttttttt
                o.....o...o...........
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##oooooo....
                oooooooooooooooooo....
                oooooooooooo..TqqqqqqT
                oooooooooooo..tttttttt
                oooooooooooo..tttTTttt
                oo....oo..oo..tttTTttt
                oo....oo..oo..tttttttt
                o.....o...o...tttttttt
                o.....o...o...tttttttt
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##..........
                oooooooooooooooo......
                oooooooooooooooo......
                oooooooooooo..oo......
                oooooooooooo.TTTTTTTTT
                oo....oo..oo.ttttTTttt
                oo....oo..oo.ttttTTttt
                o.....o...o..ttttttttt
                o.....o...o..ttttttttt
                """,
                """
                oooooooooooo..........
                oooooooooooo..........
                oo##oooooo##..........
                oo##oooooo##..........
                oooooooooooooooo......
                oooooooooooooooo....m.
                oooooooooooo..oo.....m
                oooooooooooo.TTTTTTTTT
                oo....oo..oo.ttttTTttt
                oo....oo..oomttttTTttt
                o.....o...o..ttttttttt
                o.....o...o.mttttttttt
                """,
            ])
        case .approve:
            // Waiting on your approval: a hand up and an amber "!" beside
            // him, waving now and then. Played in place of the badge dot.
            return Reel(rhythm: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
                        poses: [
                """
                ...............oo.....
                ...............oo..yy.
                ..oooooooooooo.oo..yy.
                ..oo##oooo##oo.oo..yy.
                ..oo##oooo##oo.oo..yy.
                ..oooooooooooo.oo.....
                ooooooooooooooooo..yy.
                ooooooooooooooooo.....
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
                """
                ................oo....
                ................oo....
                ..oooooooooooo.oo..yy.
                ..oo##oooo##oo.oo..yy.
                ..oo##oooo##oo.oo..yy.
                ..oooooooooooo.oo..yy.
                ooooooooooooooooo.....
                ooooooooooooooooo..yy.
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
            ])
        case .ask:
            // A question waiting on you: the same raised hand, with a
            // blue "?".
            return Reel(rhythm: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
                        poses: [
                """
                ...............oo..vv.
                ...............oo.v..v
                ..oooooooooooo.oo....v
                ..oo##oooo##oo.oo...v.
                ..oo##oooo##oo.oo..v..
                ..oooooooooooo.oo.....
                ooooooooooooooooo..v..
                ooooooooooooooooo.....
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
                """
                ................oo....
                ................oo.vv.
                ..oooooooooooo.oo.v..v
                ..oo##oooo##oo.oo....v
                ..oo##oooo##oo.oo...v.
                ..oooooooooooo.oo..v..
                ooooooooooooooooo.....
                ooooooooooooooooo..v..
                ..oooooooooooo........
                ..oooooooooooo........
                ..o.o......o.o........
                ..o.o......o.o........
                """,
            ])
        case .sleep:
            // Asleep, eyes shut, breathing, a small z and then a big one
            // drifting up. Pose 0 is the still picture the menu bar
            // shows; only the island plays the loop.
            return Reel(rhythm: [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0,
                                 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
                                 4, 4],
                        poses: [
                """
                ..............mmm.mmmm
                ................m....m
                ...............m....m.
                ..............mmm..m..
                ..oooooooooooo....mmmm
                ..oooooooooooo........
                ..oooooooooooo........
                oooo##oooo##oooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..oooooooooooo........
                """,
                """
                ......................
                ......................
                ......................
                ......................
                ..oooooooooooo........
                ..oooooooooooo........
                ..oooooooooooo........
                oooo##oooo##oooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..oooooooooooo........
                """,
                """
                ..............mmm.....
                ................m.....
                ...............m......
                ..............mmm.....
                ......................
                ..oooooooooooo........
                ..oooooooooooo........
                ..oooooooooooo........
                oooo##oooo##oooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                """,
                """
                ..............MMM.mmmm
                ................M....m
                ...............M....m.
                ..............MMM..m..
                ..................mmmm
                ..oooooooooooo........
                ..oooooooooooo........
                ..oooooooooooo........
                oooo##oooo##oooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                """,
                """
                ..................MMMM
                .....................M
                ....................M.
                ...................M..
                ..oooooooooooo....MMMM
                ..oooooooooooo........
                ..oooooooooooo........
                oooo##oooo##oooo......
                oooooooooooooooo......
                ..oooooooooooo........
                ..oooooooooooo........
                ..oooooooooooo........
                """,
            ])
        }
    }
}
