import Cocoa

/// Bug Hunt's pictures, in the same text-art format as `BreakGameArt` and drawn
/// with its palette plus the field's greens and browns. The bugs are Take a
/// break's: seen from the side while they fly (a template coloured per kind), and
/// from the front when a shot freezes them. The dog is ours too.
///
/// | Mark | Drawn as |
/// | --- | --- |
/// | `b` `B` `e` `a` `f` `h` `l` | bug template: body, shade, eye, antenna tip, wing, wing light, legs |
/// | `c` | pale wing |
/// | `l` `L` | leaf, leaf in shade (after the template is coloured) |
/// | `k` `K` | trunk, trunk in shade |
/// | `m` `M` | grass, grass in shade |
/// | `s` `S` | shell, shell brass |
/// | `d` `D` `W` `t` | dog: tan, ears, white, tongue (`o` is his collar) |
/// | everything else | as `BreakGameArt.palette` |
enum HuntGameArt {
    static let palette: [Character: UInt32] = BreakGameArt.palette.merging([
        "c": 0xc9d6ea, "l": 0x8fd14f, "L": 0x3e8f3a, "k": 0x8a5a33, "K": 0x5e3a1f,
        "m": 0x58b23c, "M": 0x2f7d2a, "s": 0xd2473b, "S": 0xd9a441,
        "d": 0xc98b4e, "D": 0x5a3a22, "W": 0xf4efe6, "t": 0xe57a8a,
    ]) { _, new in new }

    static let sky: UInt32 = 0x6cb4f0
    /// The sky while something gets away.
    static let skyAlarmed: UInt32 = 0xf2b49a
    static let grass: UInt32 = 0x58b23c
    static let dirt: UInt32 = 0x9a6438
    static let dirtDark: UInt32 = 0x6e4526

    // MARK: - Bugs

    /// Facing right, three wing beats. Coloured per kind by `bugColours`.
    static let flyTemplate = ["""
    ....ff.........
    ...fhhf........
    ...fhhf....a...
    ....fhf...a....
    .....ff..bbb...
    ..bbbbbbbbbbbb.
    .bBbBbBbbbbebb.
    bBbBbBbBbbbbbb.
    .bBbBbBbbbbbb..
    ..l..l..l......
    """, """
    ...............
    ...............
    ...........a...
    ..........a....
    .........bbb...
    ..bbbbbbbbbbbb.
    fhhhfBbBbbbebb.
    ffffBbBbBbbbbb.
    .bBbBbBbbbbbb..
    ..l..l..l......
    """, """
    ...............
    ...............
    ...........a...
    ..........a....
    .........bbb...
    ..bbbbbbbbbbbb.
    .bBbBbBbbbbebb.
    bBbBffBbBbbbbb.
    .bBfhhfbbbbbb..
    ..lfhhf.l......
    """]

    static let bugColours: [BreakGame.Kind: [Character: Character]] = [
        .drone: ["b": "v", "B": "V", "e": "#", "a": "r", "f": "c", "h": "w", "l": "V"],
        .wasp: ["b": "y", "B": "Y", "e": "#", "a": "r", "f": "g", "h": "w", "l": "Y"],
        .boss: ["b": "p", "B": "P", "e": "#", "a": "y", "f": "c", "h": "w", "l": "P"],
    ]

    static func colour(_ template: String, _ kind: BreakGame.Kind) -> String {
        let map = bugColours[kind] ?? [:]
        return String(template.map { map[$0] ?? $0 })
    }

    static func flipped(_ art: String, horizontally: Bool = true) -> String {
        let lines = art.split(separator: "\n").map(String.init)
        if horizontally { return lines.map { String($0.reversed()) }.joined(separator: "\n") }
        return lines.reversed().joined(separator: "\n")
    }

    // MARK: - The dog

    /// The hunting dog: a tan beagle with dark ears and Clawd's orange for a
    /// collar. Front view to show the catch — one paw up, or both for two.
    static let dogHold = ["""
    .....................WW.
    ........dddddddd.....WW.
    ......dddddddddddd...dd.
    ....DDdd#dddddd#ddDD.dd.
    ...DDDdd#dddddd#ddDDDdd.
    ...DDDddddWWWWddddDDDdd.
    ...DDDdddWW##WWdddDDDdd.
    ....DDddddWWWWddddDD.dd.
    ......dddWWttWWddd..dd..
    .......ooooooooooodd....
    ......dddWWWWWWdddd.....
    .....ddddWWWWWWdddd.....
    .....ddddWWWWWWdddd.....
    .....dddddddddddddd.....
    """, """
    .WW.................WW..
    .WW.....dddddddd....WW..
    .dd...dddddddddddd..dd..
    .dd.DDdd#dddddd#ddDDdd..
    .ddDDDdd#dddddd#ddDDDd..
    .ddDDDddddWWWWddddDDDd..
    .ddDDDdddWW##WWdddDDDd..
    .dd.DDddddWWWWddddDDdd..
    ..dd..dddWWttWWddd.dd...
    ....ddooooooooooodd.....
    ......dddWWWWWWdddd.....
    .....ddddWWWWWWdddd.....
    .....ddddWWWWWWdddd.....
    .....dddddddddddddd.....
    """]

    /// Laughing at you: eyes shut, mouth open — two frames.
    static let dogLaugh = ["""
    ........dddddddd........
    ......dddddddddddd......
    ....DDddddddddddddDD....
    ...DDDdd##dddd##ddDDD...
    ...DDDddddWWWWddddDDD...
    ...DDDdddWW##WWdddDDD...
    ....DDddWWWWWWWWddDD....
    ......ddW######Wdd......
    ......ddWW#tt#WWdd......
    .......ooooooooooo......
    ......dddWWWWWWdddd.....
    ....ddddWWWWWWWWdddd....
    .....dddWWWWWWWWddd.....
    .....dddddddddddddd.....
    """, """
    ........................
    ........dddddddd........
    ......dddddddddddd......
    ....DDddddddddddddDD....
    ...DDDdd##dddd##ddDDD...
    ...DDDddddWWWWddddDDD...
    ...DDDdddWW##WWdddDDD...
    ....DDddWW#tt#WWddDD....
    ......ddWWWWWWWWdd......
    .......ooooooooooo......
    ......dddWWWWWWdddd.....
    ...ddddWWWWWWWWWWdddd...
    .....dddWWWWWWWWddd.....
    .....dddddddddddddd.....
    """]

    /// Side view for the walk-in: two steps.
    static let dogWalk = ["""
    ..................dddd..
    .................dddddd.
    .d..............dd#dddd#
    .dd............DDdddddd#
    ..d...........DDDddWWW..
    ..ddddddddddddDDdWWW....
    ..ddddddddddddooo.......
    ..dddWWWWWWWWddd........
    ..ddWWWWWWWWWWdd........
    ...dd.dd....dd.dd.......
    ...dd.dd....dd.dd.......
    ...WW.WW....WW.WW.......
    """, """
    ..................dddd..
    .................dddddd.
    .d..............dd#dddd#
    .dd............DDdddddd#
    ..d...........DDDddWWW..
    ..ddddddddddddDDdWWW....
    ..ddddddddddddooo.......
    ..dddWWWWWWWWddd........
    ..ddWWWWWWWWWWdd........
    ...ddd.dd..ddd.dd.......
    ..dd....dd.dd...dd......
    ..WW....WW.WW...WW......
    """]

    /// Nose in the grass.
    static let dogSniff = """
    ........................
    ........................
    .d......................
    .dd.....................
    ..d.................dddd
    ..dddddddddddd.....ddddd
    ..ddddddddddddDD..dd#ddd
    ..dddWWWWWWWWDDDddddddd#
    ..ddWWWWWWWWWWDDddWWW...
    ...dd.dd....dd.ooWWW....
    ...dd.dd....dd.dd.......
    ...WW.WW....WW.WW.......
    """

    // MARK: - The field

    static let tree = """
    .........LLLLLL...........
    .......LLllllllLL.........
    .....LLllllllllllLL.......
    ....LlllllLLlllllllL......
    ...LllllllllllllLlllL.....
    ..LllLLllllllllllllllL....
    ..LlllllllllLLlllllllL....
    .LllllllllllllllllLllL....
    .LlllLlllllllllllllllL....
    .LllllllllllLlllllllLL....
    ..LLlllllllllllllllL......
    ...LLLlllLLlllllLLL.......
    .....LLLL.kkLLLLL.........
    ..........kK..............
    ..........kK..............
    ..........kK..............
    ..........kK..............
    ..........kK..............
    ..........kK..............
    ..........kK..............
    ..........kK..............
    ..........kK..............
    ..........kK..............
    .........kkKK.............
    """

    static let bush = """
    ....LLLL......LLL...
    ..LLllllLL..LLlllL..
    .LllllllllLLllllllL.
    LllllLlllllllllLlllL
    LlllllllllllllllllLL
    """

    /// The grass's ragged top, tiled across the field.
    static let grassEdge = """
    .M....l.....
    .M...ll..M..
    MM.l.lM..MM.
    MMmlmlMm.MMm
    mMmlmmMmmMmm
    mmmmmmmmmmmm
    mMmmmMmmmmMm
    mmmmmmmmmmmm
    """

    // MARK: - Scoreboard

    /// One per bug of the round: white to come, red when hit.
    static let icon = """
    .w...w.
    ..www..
    .wwwww.
    wwwwwww
    .w.w.w.
    """

    static let shell = """
    .s.
    sss
    sss
    sss
    SSS
    SSS
    SSS
    """

    /// Every picture, for the art test.
    static var all: [String] {
        BreakGame.Kind.allCases.flatMap { k in flyTemplate.map { colour($0, k) } }
            + [dogSniff, tree, bush, grassEdge, icon, shell] + dogHold + dogLaugh + dogWalk
    }

    static func image(_ art: String, pixel: CGFloat) -> CGImage? {
        BreakGameArt.image(art, pixel: pixel, colors: palette)
    }
}
